name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  flake:
    name: Flake_it_harder
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Update pip
        run: python -m pip install -U pip
      - name: Install flake8
        run: python -m pip install flake8==4.0.1 flake8-variables-names==0.0.5
      - name: Flake me like one of your french
        run: flake8
  
  test:
    name: Test_it_better
    needs: Flake_it_harder
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependency
        run: python -m pip install tortoise-orm pytest pytest-asyncio
      - name: Run tests
        run: python -m pytest tests/test_db.py --asyncio-mode=strict
      
  build:
    name: Build_it_faster
    needs: Test_it_better
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env: 
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: docker build -f Dockerfile -t bot:1.0 .
